create table CUSTOMERS
(
    id           int generated by default as identity primary key,
    name         varchar(255) not null,
    surname      varchar(255) not null,
    age          int          not null,
    phone_number varchar(255) not null
);

create table ORDERS
(
    id           int generated by default as identity primary key,
    date         timestamp    not null,
    customer_id  int references customers (id),
    product_name varchar(255) not null,
    amount       int          not null

);